/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Harlie/Kaeul (https://sketchfab.com/harleymh)
license: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
source: https://sketchfab.com/3d-models/engineer-space-rigged-f71089cee0674033ab0fe6b1563d5793
title: Engineer Space Rigged
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/modelDraco.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, -1.7, 0]} scale={3} rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <primitive object={nodes._rootJoint} />
          <mesh geometry={nodes.TORSO_Space_Bag_Engineer_TORSO_Space_Material_0.geometry} material={materials.Engineer_TORSO_Space_Material} />
          <skinnedMesh geometry={nodes.Object_151.geometry} material={materials.Engineer_HEAD_Space_Material} skeleton={nodes.Object_151.skeleton} />
          <skinnedMesh geometry={nodes.Object_153.geometry} material={materials.Engineer_TORSO_Space_Material} skeleton={nodes.Object_153.skeleton} />
          <skinnedMesh geometry={nodes.Object_157.geometry} material={materials.Engineer_LEGS_Space_Material} skeleton={nodes.Object_157.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/modelDraco.gltf')
